(cl:defpackage robotino_vision-srv
  (:use )
  (:export
   "GETPUCKSPOLARCOORDINATES"
   "<GETPUCKSPOLARCOORDINATES-REQUEST>"
   "GETPUCKSPOLARCOORDINATES-REQUEST"
   "<GETPUCKSPOLARCOORDINATES-RESPONSE>"
   "GETPUCKSPOLARCOORDINATES-RESPONSE"
  ))

