/* Auto-generated by genmsg_cpp for file /home/robotino/fuerte_workspace/sandbox/robotino/robotino_msgs/msg/MotorReadings.msg */
#ifndef ROBOTINO_MSGS_MESSAGE_MOTORREADINGS_H
#define ROBOTINO_MSGS_MESSAGE_MOTORREADINGS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robotino_msgs
{
template <class ContainerAllocator>
struct MotorReadings_ {
  typedef MotorReadings_<ContainerAllocator> Type;

  MotorReadings_()
  : stamp()
  , velocities()
  , positions()
  , currents()
  {
  }

  MotorReadings_(const ContainerAllocator& _alloc)
  : stamp()
  , velocities(_alloc)
  , positions(_alloc)
  , currents(_alloc)
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _velocities_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  velocities;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _positions_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  positions;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _currents_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  currents;


  typedef boost::shared_ptr< ::robotino_msgs::MotorReadings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::MotorReadings_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MotorReadings
typedef  ::robotino_msgs::MotorReadings_<std::allocator<void> > MotorReadings;

typedef boost::shared_ptr< ::robotino_msgs::MotorReadings> MotorReadingsPtr;
typedef boost::shared_ptr< ::robotino_msgs::MotorReadings const> MotorReadingsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_msgs::MotorReadings_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_msgs::MotorReadings_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_msgs::MotorReadings_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_msgs::MotorReadings_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::MotorReadings_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3974e9bd8305667fc0637697b49a8e1f";
  }

  static const char* value(const  ::robotino_msgs::MotorReadings_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3974e9bd8305667fULL;
  static const uint64_t static_value2 = 0xc0637697b49a8e1fULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::MotorReadings_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_msgs/MotorReadings";
  }

  static const char* value(const  ::robotino_msgs::MotorReadings_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::MotorReadings_<ContainerAllocator> > {
  static const char* value() 
  {
    return "time stamp\n\
float32[] velocities 	# in rpm\n\
int32[] positions\n\
float32[] currents		# in A\n\
";
  }

  static const char* value(const  ::robotino_msgs::MotorReadings_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_msgs::MotorReadings_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
    stream.next(m.velocities);
    stream.next(m.positions);
    stream.next(m.currents);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MotorReadings_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::MotorReadings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_msgs::MotorReadings_<ContainerAllocator> & v) 
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.velocities[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.positions[i]);
    }
    s << indent << "currents[]" << std::endl;
    for (size_t i = 0; i < v.currents.size(); ++i)
    {
      s << indent << "  currents[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.currents[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_MOTORREADINGS_H

