/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_msgs/msg/SetGrapplerAxis.msg */
#ifndef ROBOTINO_MSGS_MESSAGE_SETGRAPPLERAXIS_H
#define ROBOTINO_MSGS_MESSAGE_SETGRAPPLERAXIS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robotino_msgs
{
template <class ContainerAllocator>
struct SetGrapplerAxis_ {
  typedef SetGrapplerAxis_<ContainerAllocator> Type;

  SetGrapplerAxis_()
  : stamp()
  , axis(0)
  , angle(0.0)
  , velocity(0.0)
  {
  }

  SetGrapplerAxis_(const ContainerAllocator& _alloc)
  : stamp()
  , axis(0)
  , angle(0.0)
  , velocity(0.0)
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef uint32_t _axis_type;
  uint32_t axis;

  typedef float _angle_type;
  float angle;

  typedef float _velocity_type;
  float velocity;


  typedef boost::shared_ptr< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetGrapplerAxis
typedef  ::robotino_msgs::SetGrapplerAxis_<std::allocator<void> > SetGrapplerAxis;

typedef boost::shared_ptr< ::robotino_msgs::SetGrapplerAxis> SetGrapplerAxisPtr;
typedef boost::shared_ptr< ::robotino_msgs::SetGrapplerAxis const> SetGrapplerAxisConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a709aba75be9516258888daf559c39d4";
  }

  static const char* value(const  ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa709aba75be95162ULL;
  static const uint64_t static_value2 = 0x58888daf559c39d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_msgs/SetGrapplerAxis";
  }

  static const char* value(const  ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> > {
  static const char* value() 
  {
    return "time stamp\n\
uint32 axis			# axis number (axes start from 0)\n\
float32 angle		# in degrees\n\
float32 velocity	# in rpm\n\
";
  }

  static const char* value(const  ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
    stream.next(m.axis);
    stream.next(m.angle);
    stream.next(m.velocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetGrapplerAxis_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_msgs::SetGrapplerAxis_<ContainerAllocator> & v) 
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "axis: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.axis);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_MSGS_MESSAGE_SETGRAPPLERAXIS_H

