/* Auto-generated by genmsg_cpp for file /home/robotino/fuerte_workspace/sandbox/robotino/robotino_vision/msg/Puck.msg */
#ifndef ROBOTINO_VISION_MESSAGE_PUCK_H
#define ROBOTINO_VISION_MESSAGE_PUCK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robotino_vision
{
template <class ContainerAllocator>
struct Puck_ {
  typedef Puck_<ContainerAllocator> Type;

  Puck_()
  : distance(0.0)
  , direction(0.0)
  {
  }

  Puck_(const ContainerAllocator& _alloc)
  : distance(0.0)
  , direction(0.0)
  {
  }

  typedef float _distance_type;
  float distance;

  typedef float _direction_type;
  float direction;

  static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  color;

  typedef boost::shared_ptr< ::robotino_vision::Puck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_vision::Puck_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Puck
typedef  ::robotino_vision::Puck_<std::allocator<void> > Puck;

typedef boost::shared_ptr< ::robotino_vision::Puck> PuckPtr;
typedef boost::shared_ptr< ::robotino_vision::Puck const> PuckConstPtr;

template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  Puck_<ContainerAllocator>::color = "\"orange\"			# puck color";

template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_vision::Puck_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_vision::Puck_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_vision

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_vision::Puck_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_vision::Puck_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_vision::Puck_<ContainerAllocator> > {
  static const char* value() 
  {
    return "863f0d057c493bd447b19804f958dbc6";
  }

  static const char* value(const  ::robotino_vision::Puck_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x863f0d057c493bd4ULL;
  static const uint64_t static_value2 = 0x47b19804f958dbc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_vision::Puck_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_vision/Puck";
  }

  static const char* value(const  ::robotino_vision::Puck_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_vision::Puck_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 distance			# puck distance in meters\n\
float32 direction			# puck direction in degrees\n\
string color=\"orange\"			# puck color\n\
\n\
";
  }

  static const char* value(const  ::robotino_vision::Puck_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_vision::Puck_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_vision::Puck_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.distance);
    stream.next(m.direction);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Puck_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_vision::Puck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_vision::Puck_<ContainerAllocator> & v) 
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_VISION_MESSAGE_PUCK_H

