/* Auto-generated by genmsg_cpp for file /home/viki/ros_workspace/robotino-ros-pkg/robotino/robotino_local_move/msg/PathPostion.msg */
#ifndef ROBOTINO_LOCAL_MOVE_MESSAGE_PATHPOSTION_H
#define ROBOTINO_LOCAL_MOVE_MESSAGE_PATHPOSTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robotino_local_move
{
template <class ContainerAllocator>
struct PathPostion_ {
  typedef PathPostion_<ContainerAllocator> Type;

  PathPostion_()
  : move_x(0.0)
  , move_y(0.0)
  , rotate(0.0)
  {
  }

  PathPostion_(const ContainerAllocator& _alloc)
  : move_x(0.0)
  , move_y(0.0)
  , rotate(0.0)
  {
  }

  typedef float _move_x_type;
  float move_x;

  typedef float _move_y_type;
  float move_y;

  typedef float _rotate_type;
  float rotate;


  typedef boost::shared_ptr< ::robotino_local_move::PathPostion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotino_local_move::PathPostion_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PathPostion
typedef  ::robotino_local_move::PathPostion_<std::allocator<void> > PathPostion;

typedef boost::shared_ptr< ::robotino_local_move::PathPostion> PathPostionPtr;
typedef boost::shared_ptr< ::robotino_local_move::PathPostion const> PathPostionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robotino_local_move::PathPostion_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robotino_local_move::PathPostion_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robotino_local_move

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::PathPostion_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robotino_local_move::PathPostion_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robotino_local_move::PathPostion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9ccf983396917dbaf59ddb09bb98d827";
  }

  static const char* value(const  ::robotino_local_move::PathPostion_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9ccf983396917dbaULL;
  static const uint64_t static_value2 = 0xf59ddb09bb98d827ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotino_local_move::PathPostion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robotino_local_move/PathPostion";
  }

  static const char* value(const  ::robotino_local_move::PathPostion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robotino_local_move::PathPostion_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 move_x		# in meters\n\
float32 move_y		# in meters\n\
float32 rotate		# in degrees\n\
\n\
";
  }

  static const char* value(const  ::robotino_local_move::PathPostion_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robotino_local_move::PathPostion_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robotino_local_move::PathPostion_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.move_x);
    stream.next(m.move_y);
    stream.next(m.rotate);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PathPostion_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotino_local_move::PathPostion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robotino_local_move::PathPostion_<ContainerAllocator> & v) 
  {
    s << indent << "move_x: ";
    Printer<float>::stream(s, indent + "  ", v.move_x);
    s << indent << "move_y: ";
    Printer<float>::stream(s, indent + "  ", v.move_y);
    s << indent << "rotate: ";
    Printer<float>::stream(s, indent + "  ", v.rotate);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOTINO_LOCAL_MOVE_MESSAGE_PATHPOSTION_H

