"""autogenerated by genpy from robotino_refbox/Game_Info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Game_Info(genpy.Message):
  _md5sum = "e6f8fa933c19a2d59891d4e40d40385f"
  _type = "robotino_refbox/Game_Info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 phase
int32 state
int64[3] time

"""
  __slots__ = ['phase','state','time']
  _slot_types = ['int32','int32','int64[3]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       phase,state,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Game_Info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.phase is None:
        self.phase = 0
      if self.state is None:
        self.state = 0
      if self.time is None:
        self.time = [0,0,0]
    else:
      self.phase = 0
      self.state = 0
      self.time = [0,0,0]

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.phase, _x.state))
      buff.write(_struct_3q.pack(*self.time))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.phase, _x.state,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 24
      self.time = _struct_3q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2i.pack(_x.phase, _x.state))
      buff.write(self.time.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.phase, _x.state,) = _struct_2i.unpack(str[start:end])
      start = end
      end += 24
      self.time = numpy.frombuffer(str[start:end], dtype=numpy.int64, count=3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3q = struct.Struct("<3q")
_struct_2i = struct.Struct("<2i")
